### ISSUE TITLE
Upload Custom Deadline Plugin

### ISSUE THREAD

**Issue by ceskvfx** [nfa-vfxim/tk-multi-deadlinereviewsubmission#1]
Hi, many thanks for these, can you upload the custom deadline plug to understand better how is working and configured? Many thanks!

**Comment by MaximumFX** [comment]
Hey, I only just now discovered your issue and hope it can still be of use. You can find the (now public) plugin here: [ShotGridReview](https://github.com/nfa-vfxim/ShotGridReview)

**Comment by ceskvfx** [comment]
Amazing! Thanks @MaximumFX
